// User types
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

export const LOGOUT = "LOGOUT";

export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

export const GET_USER_INFO_REQUEST = "USER_INFO_REQUEST";
export const GET_USER_INFO_SUCCESS = "USER_INFO_SUCCESS";
export const GET_USER_INFO_FAILURE = "USER_INFO_FAILURE";
//
//
// Nav types
export const CHANGING_SCREEN = "CHANGING_SCREEN";
export const SHOW_BOTTOM_BAR = "SHOW_BOTTOM_BAR";
export const CLOSE_BOTTOM_BAR = "CLOSE_BOTTOM_BAR";
export const SHOW_MOBILEPLAYER = "SHOW_MOBILEPLAYER";
export const HIDE_MOBILEPLAYER = "HIDE_MOBILEPLAYER";
//
//
// Alert types
export const SHOW_ALERT = "SHOW_ALERT";
export const HIDE_ALERT = "HIDE_ALERT";
//
//
// Player types
export const PLAY_SONG_REQUEST = "PLAY_SONG_REQUEST";
export const PLAY_SONG_SUCCESS = "PLAY_SONG_REQUEST_SUCCESS";

export const RESUME_PLAY = "RESUME_PLAY";
export const PAUSE_SONG = "PAUSE_SONG";
export const PLAY_NEXT_SONG = "NEXT_SONG";
export const PLAY_PREV_SONG = "PREV_SONG";
export const SONG_GET_CURRENTTIME = "SONG_GET_CURRENTTIME";
export const SONG_GET_DURATION = "SONG_GET_DURATION";
export const SEEK_TO_REQUEST = "SEEK_TO_REQUEST";
export const SHOW_VISUALIZATION = "SHOW_VISUALIZATION";
export const HIDE_VISUALIZATION = "HIDE_VISUALIZATION";

// Playlist types
export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const SELECT_PLAYLIST = "SELECT_PLAYLIST";
